name: Gradle build

on:
  push:
    branches: [ dev, master ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-graalvm@5.0
        with:
          graalvm: 22.0.0.2
          java: java11
          arch: amd64
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - uses: gradle/wrapper-validation-action@v1.0.4
      - name: Build
        run: ./gradlew build --build-cache --no-daemon --stacktrace
